name: Feature Request
description: Suggest an idea or enhancement for the xAI Python SDK
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement to the xAI Python SDK. Please provide as much detail as possible to help us understand your idea.
  - type: checkboxes
    id: issue-source
    attributes:
      label: Confirmation of Request Source
      description: Please confirm that this feature request is related to the xAI SDK Python library and not the underlying xAI API. Requests related to the xAI API (e.g., new model features or API endpoints) should be reported through the appropriate xAI support channels (support@x.ai).
      options:
        - label: I confirm that this feature request is for the xAI SDK Python library (e.g., client features, SDK methods, or documentation) and not for the xAI API itself (e.g., model capabilities or API changes).
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of the feature or enhancement you are requesting.
      placeholder: I would like the SDK to...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the feature request here.
      placeholder: Any additional information or use cases...
    validations:
      required: false
